### ISSUE TITLE
Dropout gradients

### ISSUE THREAD

**Issue by M1ngXU** [coreylowman/dfdx#110]
That [line](https://github.com/coreylowman/dfdx/blob/d7037549c3df0e0507bbe2269e7aee0f974324ba/src/tensor_ops/impl_dropout.rs#L26) sets the gradients to 0 if the `dropout(x)` at that index is greater than 0. Since the type is `f32`, x might already be negative or 0, but in that case the gradient shouldn’t be set to 0.

I am not 100% sure if I am right, though I’d probably create some tests with Tensors that are not `3.0`, but negative or zero.

**Comment by coreylowman** [comment]
Great find, I think you're right!

**Comment by M1ngXU** [comment]
Ok, will you change the code or should I do it later?
And also, how to find wheather a ‘value’ has been dropped out or x is just 0, as both would return 0?

**Comment by coreylowman** [comment]
If you want to contribute the fix & test go for it! I don't think we can use map_df_uses_fx since we do need to know the difference between 0.0 and things that have been dropped out. You'll probably need to revert the change in this recent commit: https://github.com/coreylowman/dfdx/commit/053984e2a2358769fe9665c8d20475de5d223ddf. That may actually not have the same bug actually.
