### ISSUE TITLE
computer vision package for dfdx

### ISSUE THREAD

**Issue by edgarriba** [coreylowman/dfdx#295]
hi! i just found this repo and i really love it.

I'm one of the authors of [kornia](https://github.com/kornia/kornia) (geometric cv for pytorch) and recently started to explore rust via this package [`kornia-rs`](https://github.com/kornia/kornia-rs).

wondering how we could collaborate together -- we envision at some extent that rust is the next thing for low level cv stuff and we want to be ready for that. Besides, are you aware of the state of cuda in rust, or other accelerators perhaps like intel gpus? We are also huge fan adopters of [dlpack](https://github.com/kornia/dlpack-rs) which we would like to leverage as much as possible.

One more question/request is that if would be possible to have the tensor library as a standalone package ? We found this barely impossible have it with pytorch, which makes torch a large dependency and somehow no very user-friendly for production outside of the nn package and non-cloud applications.

/cc tagging some cv folks in the kornia surroundings for awareness @ducha-aiki @stevenlovegrove @strasdat @t-vi

**Comment by coreylowman** [comment]
Hey yeah I'd love to collaborate!

1. State of CUDA in rust is a bit of a mixed bag TBH - There's a number of crates linked too in comments in #9 with other crates that attempt to support CUDA, but I'd say they aren't production ready or seem abandoned.
2. dlpack looks really awesome at first glance, will check this out!
3. For standalone package, yeah I see the vision/problems with torch as it is now. It will be a bit different with rust since it'll only compile what you need and dfdx wouldn't be a monster pre-compiled binary. Can you expand more on the not very user-friendly for production part?

**Comment by coreylowman** [comment]
Quick update: cuda support is now in dfdx. Internally we are using something similar to dlpack (standard strided arrays), but its custom.

I've decided that application specific code will be in separate crates. For example, I've just start building out an [image classification](https://github.com/coreylowman/image-classification) crate, which will be along the same lines as torchvision.

Similarly there could be image segmentation/etc, but each of these will require different datasets/metrics/preprocessing/etc.

Will close this issue for now. Thanks for opening!
