### ISSUE TITLE
Add dynamic batch example for tensor ops & nn

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#308]
Show case the new dynamic shapes!!

**Comment by Narsil** [comment]
Hi,

Thanks for this lib. I was trying it out, however I don't seem to be able to make any real use of dynamic shape tensors.

In the context of NLP, sequence lengths are arbitrary (decided by how the tokenizer actually tokenizes a String) so it's really important to be able to work with dynamic shapes for suchs models.

I tried to do: 
```rust
let dynamic: Tensor<(usize, Const<3>, Const<4>)> = dev.zeros();
```
Seems to compile, but that's about it, it seems to be strictly equivalent to `Const<0>` which despite being nice is pretty useless (since you can't have data or do anything with it).

Did I miss something ?

Also since multiple axes could be dynamic (like batch size too) it would be nice to be able to keep having compile time guarantees. 
Like `Tensor<Dyn<B>, Dyn<SEQ_LENGTH>, Const<3>, Const<4>>`  so that further computation could be still statically checked, despite not knowing neither B not seq_length at compile time.

**Comment by coreylowman** [comment]
Thanks for the feedback @Narsil 

> `let dynamic: Tensor<(usize, Const<3>, Const<4>)> = dev.zeros();`

Ahhh yes you shouldn't be able to do this actually, that's a bug (originally when Dyn was used instead of usize, Dyn didn't implement default).

Instead you should use `zeros_like`:
```rust
let dynamic: Tensor<(usize, Const<3>, Const<4>)> = dev.zeros_like(&(5, Const, Const));
// or
let dynamic = dev.zeros_like(&(5, Const::<3>, Const::<5>));
```

This is part of why this example needs to be added because the zeros_like/ones_like/sample_uniform_like/etc isn't used anywhere else yet.

> Like `Tensor<Dyn<B>, Dyn<SEQ_LENGTH>, Const<3>, Const<4>>` so that further computation could be still statically checked, despite not knowing neither B not seq_length at compile time.

Can you expand on what `B` and `SEQ_LENGTH` would be in this case? I'm all for more compile time guarantees, just want to make sure they are actually guarantees. At compile time, only types can be compared, so even if you did something like:

```rust
fn do_something<A: Dim, B: Dim>(a: Tensor<(A, B)>, b: Tensor<(A, B)>) {}
```
this would not guarantee that the shapes are equivalent, just that the types of the dimensions are equivalent. So I could pass shapes like `(5, Const<3>)` and `(7, Const<3>)` and it would pass at compile time.

If you have any ideas on how to get around this I'd love to hear!

**Comment by Narsil** [comment]
This is sooo nice I tried to figure it out but couldn't.

There's no way to "grow" tensors, right, you would need to create another one from a different dynamic shape, and manually copy the data, correct ?
(It's fine, it's just easier to work with in the context of growing sequence_length in the context of text generation).

> Can you expand on what B and SEQ_LENGTH would be in this case? 

Ok, the use case I have in mind is something like https://github.com/huggingface/text-generation-inference (Not saying we're going to switch anytime soon, but it's the easiest example I have in mind).

The tl;dr is :
- You have a webserver doing inference for a text-generation model (like gpt2).
- You want to handle as many requests per second as possible.
- You are memory bound (meaning getting the batch size a high a possible is going to be beneficial since this is GPU).

In that context, we're going to have a "single" tensor of size <BATCH_SIZE, SEQUENCE_LENGTH> (sequence_length is the longest of all, the other requests will just be padded).

When a request comes in it gets added to the batch so `B` -> `B+1`. And you keep looping your forward loop finding the new tokens to generate (each loop means `S` -> `S+1`. )
Whenever a request is finished (either the generated the amount of expected tokens, or they generated the EOS token) then this request is done: `B` -> `B-1`. If it was the longest sequence_length find the second longest and make it smaller.

It's a little more complex in the codebase I linked, but the gist is there.

Now for the model code base, you get these tensors where you usually have `<B, S, ....> ` but in the Attention, you end up havving `<B, NUM_HEADS, S, HEADS>`  for instance, so keeping track of which is B and which is S might be convenient.

As for the typing solution, given the great type work, I'm not sure I'll be the best to answer. But since `Const<5>` isn't  `Const<3>` isn't  char litteral useable :

```rust
fn check_size<const N: char>(){
    println!("N {N:?}");
}

 fn main(){
     check_size::<'B'>()
 }
 ```
 And since `Dyn` used to be there, I felt like `Dyn<'B'> , Const<5>` was something looking nicely consistent.
 Not sure about the implications for the rest of the types.

**Comment by coreylowman** [comment]
> There's no way to "grow" tensors, right, you would need to create another one from a different dynamic shape, and manually copy the data, correct ?

Not right now at least, there's issues for #325 and #43, and I'm sure we they could be used for this.


Interesting idea with the `char`, I'll think more on it. It would be great to reduce the number of Const dims required in attention atm - batch and seq dim are expected as Const to ensure the multiple inputs have the same size.
