### ISSUE TITLE
Implement cuda kernels for optimizers

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#344]
- [ ] Sgd
- [ ] RMSprop
- [ ] Adam

Unsure if Option<X>/enums can be `#repr(c)`, so may have to change kernel op representation for these

**Comment by M1ngXU** [comment]
options can be used in ffi for c and enums are repr c (i32 by default i think)

**Comment by coreylowman** [comment]
@M1ngXU want to work on these while I figure out cudnn stuff?

**Comment by M1ngXU** [comment]
> @M1ngXU want to work on these while I figure out cudnn stuff?

ok, i'll try it when i have time, though tbh i have no idea how optimizers work 😅

**Comment by coreylowman** [comment]
They are pretty straightforward actually! You should be able to pretty much just copy the cpu kernel logic. inside the kernel, so the main thing is just create the kernel cuda function with the correct parameters & calling it correctly (you can look at how the binary/unary ops are launched for examples).

And you won't have to worry about strides at all, so no concerns about multiple concurrent writes!

**Comment by M1ngXU** [comment]
ok, but currently i am a bit short of time but i’ll implement these once i have time (but meanwhile somebody else can implement these if they want to do so)

**Comment by nkoppel** [comment]
I might go ahead and try to implement these. I was thinking that I should convert the optimizer configs into layouts that are easier to use with `#[repr(C)]` instead of having to deal with tagged unions and with Option not having a defined layout. See [here](https://github.com/rust-lang/rfcs/blob/master/text/2195-really-tagged-unions.md) for how enums with data are represented with repr C.

**Comment by coreylowman** [comment]
Yeah I was thinking the same thing would have to be done, seems reasonable to me!

**Comment by nkoppel** [comment]
This should be closed by #378.
