### ISSUE TITLE
Detect gpu architecture in `build.rs` and pass `--gpu-architecture` flag to nvcc

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#438]
Unsure how to detect as of now, so part of this issue is to figure that out!

**Comment by Narsil** [comment]
`nvidia-smi --query-gpu=compute_cap --format=csv`

Or 

```
cudaDeviceProp deviceProp;
cudaGetDeviceProperties(&deviceProp, dev);
std::printf("%d.%d\n", deviceProp.major, deviceProp.minor)

Might be better though (nvidia-smi is not necessarily installed)
https://stackoverflow.com/questions/48283009/nvcc-get-device-compute-capability-in-runtime
```

**Comment by JoeOsborn** [comment]
Two questions on this:
1. Is `-arch=native` what is being asked for here?
2. Would `-arch=all` or `-arch=all-major` be a better choice for release builds?

Otherwise you might need to get the device name(s) and check them against this list or something: https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#gpu-feature-list

**Comment by Narsil** [comment]
> Would -arch=all or -arch=all-major be a better choice for release builds?

I think not, one asset of being a compiled framework, is that we can make it highly optimized for the highest possible compute capability making small and efficient binaries for a specific platform it's supposed to work on. 

Making this overridable for users that want to create shared binaries would be good. But I don't think it should be the default.

**Comment by coreylowman** [comment]
Oh `-arch=native` seems exactly what we want! Easy change too, thanks for sharing that
