### ISSUE TITLE
JIT compile cuda kernels

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#630]
As shown in #626, with the next cudarc release, it will be possible to JIT compile cuda kernels.

_Originally posted by @coreylowman in https://github.com/coreylowman/dfdx/issues/626#issuecomment-1487608378_

Blocking questions for this:
1. What kernels should we JIT compile?
2. What, if any, values should we inline into the kernel while compiling? Possible options may be:
    a. Operation parameters (e.g. for conv2d we could inline stride/kernel/padding)
    b. Num elements
    c. num dimensions
    d. shape
    e. strides

**Comment by nkoppel** [comment]
I've already posted some of my stance on this in #626, but I'll restate and clarify it here. 

In general, it should be fine to inline anything that is known at compile-time, but most runtime values should be passed in, assuming JIT compilations take at least 10 ms. This is because inlining variables that take on several values during execution would cause a significant slowdown. For example, shape and stride should not be included because users may run their networks on a large variety of input sizes, when could occur when running a cnn on unscaled and uncropped images from the internet.

As long as we keep the number of compilations small, there shouldn't be much downside to JIT compiling every operation, except for slow startup.

**Comment by coreylowman** [comment]
We could do different things in training vs inference - since training will have very regular inputs, however I think it'd be too complex internally to have a feature flag to swap between jit vs ahead of time IMO. So not inlining shapes/strides makes sense to me

**Comment by coreylowman** [comment]
I think the biggest wins here will be with kernels that need to work with many different types. Also kernels that are more niche that are less likely to be used so we don't have to compile them unless they are used
