### ISSUE TITLE
Remove alloc_zeros from sum_to, fill_with from max_to/min_to

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#646]
- sum_to should use alloc, and then inside the kernel it can set out[i / chunk_len] = 0 before calling chunk_sum
- min_to/max_to can also use alloc, and also inside the kernel set values to either `-INFINITY`/`INFINITY`.

The threads should only set the values if `i % chunk_len == 0`

**Comment by nkoppel** [comment]
Doing this would be unsound, as threads from different blocks may chunk_sum to the same location, which with these changes would cause values to be ignored.

**Comment by coreylowman** [comment]
Even if we do (for example in sum):
```rust
if (i % chunk_len == 0) {
   out[i / chunk_len] = 0;
}
__syncthreads();
```
?

**Comment by nkoppel** [comment]
That might be ok? it mainly depends on whether blocks run in order of their index, which may or may not always be true, because 'syncthreads' is only able to synchronize all threads in a single block. It may still produce incorrect output if block run out-of-order because some threads would be writing to uninitialized memory before it gets zeroed.

**Comment by coreylowman** [comment]
Hmm okay I see. Will keep thinking about this then. Might be moving to cudnn for reduction forward regardless, so this may not be relevant?
