### ISSUE TITLE
Stack overflow when using .array()

### ISSUE THREAD

**Issue by mlupo19** [coreylowman/dfdx#669]
Code to reproduce error:
```
use dfdx::{tensor::{AutoDevice, AsArray}, prelude::{DeviceBuildExt, Linear}};
fn main() {
    let dev = AutoDevice::default();

    let linear = dev.build_module::<Linear<784, 512>, f32>();

    linear.weight.array();
}
```
Error:
```
thread 'main' has overflowed its stack
error: process didn't exit successfully: `target\release\testing.exe` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)
```

Environment:
Windows 11 x64 using Cpu (haven't tested with Cuda device)
16GB RAM

Notes:
- Switching weight with bias does not produce the error

**Comment by coreylowman** [comment]
Yeah this is because you are trying to create a `[[f32; 512]; 784]` sized array on the stack, which is 1.6Mb. You can use `linear.weight.as_vec()` to extract the data as a flat `Vec<f32>` on the heap. You can also save a tensor to a `.npy` or `.safetensor` file with the corresponding feature flag if you want to work with it in array form somewhere else.

Closing this for now as this is entirely expected. If you have an idea of a better way to handle this, feel free to open a new issue with a feature request!
