### ISSUE TITLE
Please clarify how gradient tapes work when you have multiple paths through your network

### ISSUE THREAD

**Issue by emchristiansen** [coreylowman/dfdx#823]
I'm trying to differentiate through a gnarly computation that looks like this:

`fn forward(&MyModel, &[CrazyInputType<Tensor<...>>]) -> Vec<CrazyOutputType<Tensor<...>>;`

Here, each element of the output vector is essentially a "head", so I want to compute the loss for each output, sum them all together, and compute the gradient of the sum wrt the model parameters.

Is this currently possible with `dfdx`?
You've written in places about the next layer in the network taking ownership of the gradient tape, but I don't always have a "next layer" - I have branches that then come back together.

Relatedly, how do you add regularization terms, e.g. l2 weight penalties?
Do you just compute the loss and regularization gradients separately and then add them?

Thanks!

**Comment by coreylowman** [comment]
All of the binary operations (add/sub/mul/div/etc) combine the tapes of both the inputs, so that is how you would combine the gradients from multiple paths.

Most of the current `nn` layer uses the [WithEmptyTape](https://docs.rs/dfdx/0.12.1/dfdx/tensor/trait.WithEmptyTape.html#tymethod.with_empty_tape) method of tensor to clone the tensor & insert a new empty gradient tape into it. E.g. residual layer does this: 

```rust
    fn try_forward(&self, x: T) -> Result<Self::Output, F::Error> {
        self.0.try_forward(x.with_empty_tape())?.try_add(x)
    }
```

https://github.com/coreylowman/dfdx/blob/main/src/nn/residual.rs#L49

Re loss regularization, yeah you'd just add them. Note that all the optimizers support an [`Option<WeightDecay>`](https://docs.rs/dfdx/0.12.1/dfdx/optim/enum.WeightDecay.html) configuration that can do the regularization as well.

Let me know if you have more questions!

**Comment by emchristiansen** [comment]
Thanks!

So IIUC, whenever I come to a split in my network (e.g. something like a residual block) with `N` branches, I need to use `.with_empty_tape()` for `N-1` of the branches, and do nothing for the last branch.
It doesn't matter which branches use `.with_empty_tape()` so long as exactly one of them doesn't use it.

Relatedly, what would happen if you had instead called `x.clone()` in the example above?
Would it also clone the tape, leading to double-counting gradients for the part of the graph traced so far?

**Comment by coreylowman** [comment]
> It doesn't matter which branches use .with_empty_tape() so long as exactly one of them doesn't use it.

Yep exactly!

> Relatedly, what would happen if you had instead called x.clone() in the example above?

You actually can't call clone on a tensor with a OwnedTape, since it doesn't impl Clone atm. We probably could impl Clone, and it would keep all the gradients (thus leading to it being double counted)
